<?php
/**
 * @file
 * Module file for the Clubul Calatorilor sendgrid module, contains all the main hooks and logic functions.
 */

use Drupal\clubulcalatorilor_sendgrid\Controller\ClubulCalatorilorSendgridController as CCSController;

/**
 * Implements hook_theme().
 */
function clubulcalatorilor_sendgrid_theme($existing, $type, $theme, $path)
{
  return array(
    'email_confirmation_template' => array(
      'variables' => array('vars' => NULL),
      'template' => 'email-confirmation-template'
    ),
    'email_reminder_template' => array(
      'variables' => array('vars' => NULL),
      'template' => 'email-reminder-template'
    ),
  );
}

/**
 * Implements hook_cron().
 */
function clubulcalatorilor_sendgrid_cron() {
  //CCSController::processEmailRemainders(1);
  //CCSController::processEmailRemainders(3);
  //CCSController::processConfirmationRemoval(15);
}
