<?php

/**
 * @file
 * Contains facebook_pixel.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function facebook_pixel_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the facebook_pixel module.
    case 'help.page.facebook_pixel':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Facebook Pixel') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_page_attachments().
 */
function facebook_pixel_page_attachments(array &$page){
  $config = \Drupal::config('facebook_pixel.facebookpixelconfig');
  $id = $config->get('facebook_id');
  $jsString = json_encode($id);
  $urlParameter = urlencode($id);

  $script = '!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod? n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version=\'2.0\';n.queue=[];t=b.createElement(e);t.async=!0;t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,document,\'script\',\'https://connect.facebook.net/en_US/fbevents.js\');fbq(\'init\', ' . $jsString . ');fbq(\'track\', "PageView");';
  $noscript = '<img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=' . $urlParameter . '&ev=PageView&noscript=1" />';

  $page['#attached']['html_head'][] = [
      [
          '#tag' => 'script',
          '#value' => $script,
      ],
      'facebook_tracking_pixel_script',
  ];

  $page['#attached']['html_head'][] = [
      [
          '#tag' => 'noscript',
          '#value' => $noscript,
      ],
      'facebook_tracking_pixel_noscript',
  ];
}