<?php
/**
 * @file
 * Module file for the Clubul Calatorilor flights importer module, contains all the main hooks and logic functions.
 */

/**
 * Implements hook_theme().
 */
function clubulcalatorilor_flights_importer_theme($existing, $type, $theme, $path)
{
  return array(
    'flights_template' => array(
      'variables' => array('vars' => NULL),
      'template' => 'flights-template'
    ),
  );
}
