<?php

/**
 * @file
 * Module file for the Clubul calatorilor module, contains all the main hooks and logic functions.
 */

use Drupal\user\Entity\User;

/**
 * Implements hook_theme().
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return array
 */
function clubulcalatorilor_theme($existing, $type, $theme, $path)
{
  return array(
    'header_sign_up_template' => array(
      'variables' => array('vars' => NULL),
      'template' => 'header-sign-up-template'
    ),
    'footer_sign_up_template' => array(
      'variables' => array('vars' => NULL),
      'template' => 'footer-sign-up-template'
    ),
    'homepage_sign_up_template' => array(
      'variables' => array('vars' => NULL),
      'template' => 'homepage-sign-up-template'
    ),
    'homepage_how_it_works_template' => array(
      'variables' => array('vars' => NULL),
      'template' => 'homepage-how-it-works-template'
    ),
    'homepage_about_us_template' => array(
      'variables' => array('vars' => NULL),
      'template' => 'homepage-about-us-template'
    ),
    'footer_block_template' => array(
      'variables' => array('vars' => NULL),
      'template' => 'footer-block-template'
    ),
    'footer_building_block_template' => array(
      'variables' => array('vars' => NULL),
      'template' => 'footer-building-block-template'
    ),
  );
}
